name: Publish with Lerna

on:
  push:
    branches:
    - master

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1.0.0
    - name: Git Identity
      run: |
        git config --global user.name 'bethon'
        git config --global user.email 'fxy1044667399@163.com'
        git remote set-url origin https://github.com/fXy-during/monorepo.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Pulling
      run: git pull
    - name: Install dependencies
      run: npm i
    - name: Authenticate with Registry
      run: |
          yarn logout
          echo "fXy-during/monorepo:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish with Lerna
      run: npx lerna publish --yes --repo-version 1.0.6
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
